### ISSUE TITLE
Session with AWS Lambdas does not persist state when it is set after an async operation. 

### ISSUE THREAD

**Issue by vtcaregorodtcev** [RealSpeaker/telegraf-session-local#181]
Hi there. 

In my project, I use a bunch of middlewares as a steps to collect data from different sources and found some strange behaviour. The user sends some links to the BOT and I save it to the session, then I invoke the next function. The next middleware is the async function and I request a page from the provided link. So, I also save some data from that page in the session. 

If I will chain another middleware after this, I will be able to get this data, but if the user will send another message this data will be lost, but the previous link anyway still stay. 

I guess this is because the link is set in a synchronous manner but data from the link is asynchronous.

**Comment by vtcaregorodtcev** [comment]
Here is the example https://github.com/vtcaregorodtcev/remark-telegram-bot/blob/main/src/handlers/telegramBot.ts#L34

at 34 line I use sync middleware to save Link to the session
at 35 I use async middleware to get data from the Link 

at 36 line I can get async data only within the same user message if the user will send another message, I lost data from 35 line.

**Comment by vtcaregorodtcev** [comment]
<img width="241" alt="Screenshot 2022-01-16 at 08 39 41" src="https://user-images.githubusercontent.com/24553355/149648711-097a4a98-b63b-4d23-ad06-ed49edf28e09.png">

**Comment by EdJoPaTo** [comment]
From experience: It worked fine with async stuff for me. But forgetting the await on something is easily done in JavaScript / TypeScript. There are some ESLints that help with finding that in TypeScript.

Personally I switched away towards grammY. It provides its own session logic and the storage is separated from the middleware logic which prevents implementation bugs there. It might be worth a look. Switching from Telegraf to grammY is relatively straight forward and grammYs documentation is way better.

**Comment by vtcaregorodtcev** [comment]
@EdJoPaTo it's also worth mentioning, my example is based on AWS setup

**Comment by EdJoPaTo** [comment]
AWS should be completely irrelevant here. Node.js is Node.js and its async/await Logic is handled the same way on all platforms. Whatever the exact problem is, you should be able to reproduce it locally. When that is possible throw out stuff in order to have a minimal example where you can still reproduce the bug. Then its way easier to find the cause of it.

What helps me with missing awaits somewhere: Create a simple logging middleware and put it in between every other middleware. If a log message comes before it should, there is a missing await.

Maybe check out my [console.time middleware for testing middlewares](https://github.com/EdJoPaTo/telegraf-middleware-console-time#test-a-middleware). If the inner is way to short or the report comes back way to early the problem is below of what you tested. If the before/after is way to short, then its the middleware you just checked.

**Comment by vtcaregorodtcev** [comment]
@EdJoPaTo sorry, it looks like I should anyway set up all AWS flow for minimal reproduction. I guess you can fork provided commit vtcaregorodtcev/remark-telegram-bot@dde683b and there is an issue. 

there is Link property which set in sync manner https://github.com/vtcaregorodtcev/remark-telegram-bot/commit/dde683bf95a71954663c226ed8728f925baad378#diff-4219770533d72f642405c1221b67774ae414f90ab05212b8b44bb2b063b62cf9R15

and Text property which set in async manner  https://github.com/vtcaregorodtcev/remark-telegram-bot/commit/dde683bf95a71954663c226ed8728f925baad378#diff-a2fb86f8d1743026e193802adeb45a908d8793046564073b63e6dcc1feade4c2R31

if we will set console.log or something here https://github.com/vtcaregorodtcev/remark-telegram-bot/commit/dde683bf95a71954663c226ed8728f925baad378#diff-5566f90f142be7d5c358410953f0b4c628c99e20b620d172c8e12ec92bdc9620R32

we will see that after each request Link is still stay but Text is missing.


to run it locally we should anyway deploy lambda to AWS to use offline serverless. 
`pnpm deploy ` then get lamda URL and `TOKEN=your_bot_token HOOK=lambda_url pnpm start`

**Comment by TemaSM** [comment]
Thanks for help @EdJoPaTo 👍 
Closing now as stale, but if someone wanna ask more - feel free to do so.
