### ISSUE TITLE
issue with nodemon

### ISSUE THREAD

**Issue by kenenisa** [RealSpeaker/telegraf-session-local#186]
Nodemon works perfectly but when I include `const LocalSession = require('telegraf-session-local')`  it keeps failing to restart like: `[nodemon] restarting due to changes...
[nodemon] starting 'node index.js'` again and again.

I'm using nodemon 2.0.15 and the latest telegraf-session-local version

**Comment by TemaSM** [comment]
Hi @kenenisa

That's an expected behavior of nodemon, because it starts watching changes of files: `[nodemon] watching extensions: js,mjs,json`.
If you look into simple example:
https://github.com/RealSpeaker/telegraf-session-local/blob/43ab64dd343c351dc5cebdbc949b8f758df91af5/examples/simple.js#L6
\- Here is `database` option which defines the path for database file of sessions, for example `example_db.json`.
`telegraf-sessin-local` uses underlying library called `lowdb` to store and manipulate database data.
When you start your bot, `lowdb` creates new file descriptor for `database`-file and touches it (look onto file modification date-time just after starting `nodemon` or `node`), which simply fires `nodemon` event like 'file was modified' and `nodemon` performing restart of your js file, which leads to looped behavior:
`--(1)-- Start js file and watch for changes by nodemon --(2)--> JS file started by node --(3)--> Bot started and touched database file --(4)--> Nodemon detected change of json file --(5)--> Nodemon re-executes js file --> (1)`

**To fix this**, please [add config for `nodemon`](https://github.com/remy/nodemon#packagejson) to ignore `json`-database file, for example by adding new block into your `package.json`: 
```json
"nodemonConfig": {
  "ignore": ["sessions.json", "example_db.json"]
}
```
`sessions.json` - default filename of sessions' database in `telegraf-session-local`:
https://github.com/RealSpeaker/telegraf-session-local/blob/43ab64dd343c351dc5cebdbc949b8f758df91af5/lib/session.js#L15

**Comment by kenenisa** [comment]
> Hi @kenenisa
> 
> That's an expected behavior of nodemon, because it starts watching changes of files: `[nodemon] watching extensions: js,mjs,json`. If you look into simple example:
> 
> https://github.com/RealSpeaker/telegraf-session-local/blob/43ab64dd343c351dc5cebdbc949b8f758df91af5/examples/simple.js#L6
> 
> 
> - Here is `database` option which defines the path for database file of sessions, for example `example_db.json`.
> `telegraf-sessin-local` uses underlying library called `lowdb` to store and manipulate database data.
> When you start your bot, `lowdb` creates new file descriptor for `database`-file and touches it (look onto file modification date-time just after starting `nodemon` or `node`), which simply fires `nodemon` event like 'file was modified' and `nodemon` performing restart of your js file, which leads to looped behavior:
> `--(1)-- Start js file and watch for changes by nodemon --(2)--> JS file started by node --(3)--> Bot started and touched database file --(4)--> Nodemon detected change of json file --(5)--> Nodemon re-executes js file --> (1)`
> **To fix this**, please [add config for `nodemon`](https://github.com/remy/nodemon#packagejson) to ignore `json`-database file, for example by adding new block into your `package.json`:
> 
> ```json
> {
>   "...": "... other standard package.json values",
>   "nodemonConfig": {
>     "ignore": ["sessions.json", "example_db.json"]
>   }
> }
> ```
> 
> `sessions.json` - default filename of sessions' database in `telegraf-session-local`:
> 
> https://github.com/RealSpeaker/telegraf-session-local/blob/43ab64dd343c351dc5cebdbc949b8f758df91af5/lib/session.js#L15

The issue is resolved. It's now working as intended.
