### ISSUE TITLE
Not all data is saved in a local file

### ISSUE THREAD

**Issue by Cit1zeN4** [RealSpeaker/telegraf-session-local#86]
Hi. I have this problem: I have 2 `scene.enter` handlers, in both I save the bot message, but one handler saves the message and the other doesn't.
```
scene.enter(async (ctx) => {
    const msg = await ctx.reply("login");
    ctx.scene.state.editMsg = { chatId: msg.chat.id, messageId: msg.message_id };
  });
```
This code works well and the message is saved
```
scene.enter(async (ctx) => {
    const msg = await ctx.replyWithPhoto(
      { source: `${process.env.rootDir}/assets/img/settings.png` },
      Extra.load({ caption: "Settings" })
        .markdown()
        .markup((m) =>
          m.inlineKeyboard([
            [m.callbackButton("Profile", "profile"), m.callbackButton("Social", "social")],
            [m.callbackButton("Wallet", "wallet"), m.callbackButton("Back", "back")],
          ])
        )
    );

    ctx.scene.state.delMsg = { chatId: msg.chat.id, messageId: msg.message_id };
  });
```
But this code doesn't save the message.
What could be the problem?
```
node: v12.16.1
npm: v6.13.4
```

**Comment by EdJoPaTo** [comment]
the default of this library is to use `ctx.session`. In this case you are using `ctx.scene.state`. Have you configured that path so its used instead of `ctx.session`?

In Telegraf terms the state is only relevant for handling this one update, the session is relevant long term. I assume its the same for the scene stuff, but I never really used it. For more readable code it might be helpful to use these terms the same as telegraf. Just as something I noticed there. :)

**Comment by Cit1zeN4** [comment]
No, I used `LocalSession` with default configuration. I know that `ctx.scene.state` is less constant compared to `ctx.session`. I just wanted to use this to store temporary data if, for example, the bot reboots while working with it to continue working from the "checkpoint".
I think it's better to close this issue for awhile. I'll run a couple of tests and if I find anything, I'll re-open it. Maybe I just made a few logical mistakes and didn't notice them.
Thanks for your reply :)
